import type { ComponentType } from 'react'
import {
  GraduationCap,
  Globe,
  Languages,
  Bot,
  Briefcase,
  Crown,
  Lightbulb,
  Heart,
  TrendingUp,
  FlaskConical,
  Smile,
  Handshake,
} from 'lucide-react'

export interface ThemeItem {
  id: string
  num: string
  title: string
  subtitle: string
  description: string
  icon: ComponentType<{ size?: number; className?: string }>
  color: string
  bgLight: string
  borderLight: string
  link: string
}

export const EMC_12_THEMES: ThemeItem[] = [
  {
    id: 'academic',
    num: '01',
    title: 'المسارات الأكاديمية',
    subtitle: 'Academic Pathways',
    description: 'إرشاد وتوجيه أكاديمي منظم ومستمر من المرحلة المدرسية إلى الجامعة والدراسات العليا.',
    icon: GraduationCap,
    color: '#1FA3DC',
    bgLight: 'bg-[#1FA3DC]/[0.08]',
    borderLight: 'border-[#1FA3DC]/25',
    link: '/tracks#academic',
  },
  {
    id: 'global',
    num: '02',
    title: 'التعلّم العالمي',
    subtitle: 'Global Learning',
    description: 'برامج فريدة وفرص تعلّم دولية عابرة للحدود لتوسيع الآفاق وبناء الفهم العالمي.',
    icon: Globe,
    color: '#F39200',
    bgLight: 'bg-[#F39200]/[0.08]',
    borderLight: 'border-[#F39200]/25',
    link: '/tracks#global',
  },
  {
    id: 'language',
    num: '03',
    title: 'معهد اللغات',
    subtitle: 'Language Institute',
    description: 'تمكين المهارات اللغوية والتواصلية المتعددة (العربية، الإنجليزية، الهولندية) لربط الثقافات.',
    icon: Languages,
    color: '#52BFEA',
    bgLight: 'bg-[#52BFEA]/[0.08]',
    borderLight: 'border-[#52BFEA]/25',
    link: '/tracks#language',
  },
  {
    id: 'ai',
    num: '04',
    title: 'الذكاء الاصطناعي والتمكين الرقمي',
    subtitle: 'AI & Digital Empowerment',
    description: 'تأهيل وتطوير القدرات التكنولوجية المتقدمة وتطبيقات الذكاء الاصطناعي للمستقبل.',
    icon: Bot,
    color: '#FCB347',
    bgLight: 'bg-[#FCB347]/[0.08]',
    borderLight: 'border-[#FCB347]/25',
    link: '/tracks#ai',
  },
  {
    id: 'career',
    num: '05',
    title: 'المهارات والتطوير المهني',
    subtitle: 'Career & Skills Development',
    description: 'إعداد الكوادر لسوق العمل وصقل المهارات الناعمة والتقنية اللازمة للتميّز الوظيفي.',
    icon: Briefcase,
    color: '#0F6E99',
    bgLight: 'bg-[#0F6E99]/[0.08]',
    borderLight: 'border-[#0F6E99]/25',
    link: '/tracks#career',
  },
  {
    id: 'leadership',
    num: '06',
    title: 'القيادة (روّاد)',
    subtitle: 'Leadership & Ruwad',
    description: 'صناعة وصقل مهارات قادة وروّاد المستقبل وفق منهجيات قيادية حديثة ورؤية طموحة.',
    icon: Crown,
    color: '#A95F00',
    bgLight: 'bg-[#A95F00]/[0.08]',
    borderLight: 'border-[#A95F00]/25',
    link: '/tracks#leadership',
  },
  {
    id: 'awareness',
    num: '07',
    title: 'الوعي والمعرفة',
    subtitle: 'Awareness & Knowledge',
    description: 'إثراء الفكر ونشر المعرفة التخصصية الشاملة والمحتوى الأكاديمي الرصين.',
    icon: Lightbulb,
    color: '#7CCEEE',
    bgLight: 'bg-[#7CCEEE]/[0.08]',
    borderLight: 'border-[#7CCEEE]/25',
    link: '/tracks#awareness',
  },
  {
    id: 'wellbeing',
    num: '08',
    title: 'الرفاه والصحة المتكاملة',
    subtitle: 'Wellbeing & Health',
    description: 'تعزيز التوازن النفسي والرفاه الذاتي والنمو المتكامل للمتعلمين والمعلمين.',
    icon: Heart,
    color: '#D77F00',
    bgLight: 'bg-[#D77F00]/[0.08]',
    borderLight: 'border-[#D77F00]/25',
    link: '/tracks#wellbeing',
  },
  {
    id: 'finance',
    num: '09',
    title: 'الوعي المالي',
    subtitle: 'Financial Literacy',
    description: 'ترسيخ ثقافة الإدارة المالية الشخصية والاستثمار الواعي والتخطيط المالي المستقبلي.',
    icon: TrendingUp,
    color: '#1488BC',
    bgLight: 'bg-[#1488BC]/[0.08]',
    borderLight: 'border-[#1488BC]/25',
    link: '/tracks#finance',
  },
  {
    id: 'experiential',
    num: '10',
    title: 'التعلّم التجريبي التطبيقي',
    subtitle: 'Experiential Learning',
    description: 'تجارب عمليّة ومحاكاة ميدانية وورش تفاعلية لتحويل المعرفة إلى ممارسة فعلية.',
    icon: FlaskConical,
    color: '#E07F00',
    bgLight: 'bg-[#E07F00]/[0.08]',
    borderLight: 'border-[#E07F00]/25',
    link: '/tracks#experiential',
  },
  {
    id: 'children',
    num: '11',
    title: 'الأطفال (عقول المستقبل)',
    subtitle: 'Children - Future Minds',
    description: 'برامج تعليمية مبتكرة لتنمية شغف الاستكشاف والابتكار والتفكير النقدي لدى الناشئة.',
    icon: Smile,
    color: '#073E58',
    bgLight: 'bg-[#073E58]/[0.08]',
    borderLight: 'border-[#073E58]/25',
    link: '/tracks#children',
  },
  {
    id: 'partnerships',
    num: '12',
    title: 'الشراكات والتحالفات',
    subtitle: 'Partnerships & Alliances',
    description: 'بناء شبكة تعاون مؤسسي وأكاديمي مع الجامعات والمراكز العالمية ذات الأثر.',
    icon: Handshake,
    color: '#FBBF24',
    bgLight: 'bg-[#FBBF24]/[0.08]',
    borderLight: 'border-[#FBBF24]/25',
    link: '/tracks#partnerships',
  },
]
