import { canAccessDashboardPath } from '@/utils/dashboardAccess'
import type { PageAccessRiskLevel } from '@/api/pageAccessCatalogApi'
import type { PageAccessSource } from '@/api/accessControlApi'

/**
 * Phase 2F — ACCESS DIFF HARNESS. MEASUREMENT ONLY.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THIS MODULE IS NOT PART OF PRODUCTION ENFORCEMENT
 * ─────────────────────────────────────────────────────────────────────────
 * Nothing in the app imports it. It exists to COMPARE the two access systems
 * before any cutover, and it must never be wired into DashboardAccessGuard,
 * dashboardAccess.ts, the sidebar or App.tsx. A test asserts that isolation.
 *
 * Both sides of the comparison are REAL, not re-implementations:
 *   LEGACY    — canAccessDashboardPath(), imported directly from the live
 *               production module and called unmodified.
 *   EFFECTIVE — the allowed-key set emitted by the backend's real
 *               EffectivePageAccessService (see the committed baseline fixture,
 *               regenerated by tests/Feature/AccessDiffBaselineTest.php).
 *
 * PAGE ACCESS != BUSINESS AUTHORIZATION: this compares page exposure only.
 */

/* ── Baseline fixture shapes (as emitted by the backend generator) ──────── */

export type BaselineCatalogEntry = {
  key: string
  primary_route: string
  route_patterns: string[]
  label_ar: string
  category: string
  risk_level: PageAccessRiskLevel
  protected: boolean
  delegatable: boolean
  department_scoped: boolean
  /** Phase 2G.2 — catalog-declared authenticated baseline. */
  authenticated_baseline: boolean
}

export type BaselinePersona = {
  role: string
  context: 'none' | 'member' | 'leader'
  note: string
  allowed: string[]
  provenance: Record<string, PageAccessSource>
}

export type AccessBaseline = {
  catalog_count: number
  catalog: BaselineCatalogEntry[]
  scenarios: Record<string, Record<string, BaselinePersona>>
}

/* ── Diff model ────────────────────────────────────────────────────────── */

export type DiffStatus =
  | 'MATCH_ALLOWED'
  | 'MATCH_DENIED'
  | 'NEWLY_ALLOWED'
  | 'NEWLY_DENIED'
  | 'UNMAPPED'

export type RiskLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'EXPECTED'

export type DiffRow = {
  key: string
  path: string
  legacyAllowed: boolean
  effectiveAllowed: boolean
  status: DiffStatus
  legacyReason: string
  effectiveReason: string
  effectivePrimarySource: PageAccessSource | null
  risk: RiskLevel
  category: string
  riskLevelOfPage: PageAccessRiskLevel
}

export type PersonaDiff = {
  personaId: string
  role: string
  context: string
  note: string
  rows: DiffRow[]
  counts: Record<DiffStatus, number>
}

/* ── 4. Path → capability matching (ONE canonical helper) ──────────────── */

/**
 * Resolve a dashboard path to the catalog capability that owns it.
 *
 * A capability owns MANY urls (index/show/create/edit variants, alternate mount
 * points), so raw-URL comparison is wrong — the match runs against
 * `route_patterns`, exact first and then LONGEST prefix, so
 * `/dashboard/admin/ai/usage` resolves to `technical_system.ai_usage` rather
 * than the shorter `technical_system.ai_command_center` (`/dashboard/admin/ai`).
 *
 * This is the only route-pattern matcher in the harness; nothing duplicates it.
 */
export function findCapabilityForPath(
  catalog: BaselineCatalogEntry[],
  path: string,
): BaselineCatalogEntry | null {
  let best: BaselineCatalogEntry | null = null
  let bestLen = -1

  for (const entry of catalog) {
    for (const pattern of entry.route_patterns) {
      if (pattern === path) return entry
      if (path.startsWith(`${pattern}/`) && pattern.length > bestLen) {
        best = entry
        bestLen = pattern.length
      }
    }
  }

  return best
}

/* ── 19. Risk classification ───────────────────────────────────────────── */

/**
 * Classify a mismatch. Deliberately conservative: anything touching a
 * SYSTEM_PROTECTED capability or a leader-only surface is escalated, and a
 * loss of access caused by the new system requiring CANONICAL leadership
 * instead of a role slug is EXPECTED rather than a defect.
 */
export function classifyRisk(
  entry: BaselineCatalogEntry,
  status: DiffStatus,
  context: string,
): RiskLevel {
  if (status === 'MATCH_ALLOWED' || status === 'MATCH_DENIED') return 'EXPECTED'
  if (status === 'UNMAPPED') return 'HIGH'

  if (status === 'NEWLY_ALLOWED') {
    // An ordinary persona gaining a protected page is the worst possible outcome.
    if (entry.protected) return 'CRITICAL'
    // Gaining a leader-only surface without canonical leadership.
    if (entry.department_scoped && !entry.delegatable && context !== 'leader') return 'HIGH'
    if (entry.risk_level === 'ADMIN_ONLY') return 'MEDIUM'
    return 'LOW'
  }

  // NEWLY_DENIED
  // Losing a role-slug-granted page because canonical leadership is now
  // required is the intended behaviour change, not a regression.
  if (entry.department_scoped && context === 'none') return 'EXPECTED'
  if (entry.protected) return 'EXPECTED'
  if (entry.category === 'personal') return 'LOW'
  if (entry.risk_level === 'ADMIN_ONLY') return 'MEDIUM'
  return 'MEDIUM'
}

/* ── 5. The comparison ─────────────────────────────────────────────────── */

const EMPTY_COUNTS: Record<DiffStatus, number> = {
  MATCH_ALLOWED: 0,
  MATCH_DENIED: 0,
  NEWLY_ALLOWED: 0,
  NEWLY_DENIED: 0,
  UNMAPPED: 0,
}

/**
 * Compare LEGACY vs EFFECTIVE for one persona, across every catalog capability.
 *
 * The legacy side is evaluated at each capability's `primary_route`, because
 * that is the URL a user actually navigates to and the one the legacy prefix
 * rules were written against.
 */
export function diffPersona(
  personaId: string,
  persona: BaselinePersona,
  catalog: BaselineCatalogEntry[],
): PersonaDiff {
  const allowedSet = new Set(persona.allowed)
  const rows: DiffRow[] = []
  const counts: Record<DiffStatus, number> = { ...EMPTY_COUNTS }

  for (const entry of catalog) {
    const path = entry.primary_route
    const legacyAllowed = canAccessDashboardPath(persona.role, path)
    const effectiveAllowed = allowedSet.has(entry.key)
    const primarySource = persona.provenance[entry.key] ?? null

    const status: DiffStatus =
      legacyAllowed && effectiveAllowed ? 'MATCH_ALLOWED'
      : !legacyAllowed && !effectiveAllowed ? 'MATCH_DENIED'
      : !legacyAllowed && effectiveAllowed ? 'NEWLY_ALLOWED'
      : 'NEWLY_DENIED'

    counts[status] += 1

    rows.push({
      key: entry.key,
      path,
      legacyAllowed,
      effectiveAllowed,
      status,
      legacyReason: legacyAllowed ? 'legacy role rule allows this path' : 'legacy role rule denies this path',
      effectiveReason:
        effectiveAllowed ?
          `effective access via ${primarySource ?? 'unknown'}`
        : 'no layer grants this capability',
      effectivePrimarySource: primarySource,
      risk: classifyRisk(entry, status, persona.context),
      category: entry.category,
      riskLevelOfPage: entry.risk_level,
    })
  }

  return { personaId, role: persona.role, context: persona.context, note: persona.note, rows, counts }
}

/** Compare every persona in one baseline scenario. */
export function diffScenario(
  scenario: Record<string, BaselinePersona>,
  catalog: BaselineCatalogEntry[],
): PersonaDiff[] {
  return Object.entries(scenario).map(([id, p]) => diffPersona(id, p, catalog))
}

/* ── 12. Unmapped legacy routes ────────────────────────────────────────── */

/**
 * Any dashboard path the legacy system knows about that NO catalog capability
 * owns. Target is zero before cutover: an unmapped route would otherwise be
 * silently denied (or silently allowed) by whichever system wins.
 */
export function findUnmappedPaths(catalog: BaselineCatalogEntry[], legacyPaths: string[]): string[] {
  return legacyPaths.filter((p) => findCapabilityForPath(catalog, p) == null)
}

/* ── 13. Sidebar comparison ────────────────────────────────────────────── */

export type SidebarDiffStatus = 'MATCH' | 'NEWLY_VISIBLE' | 'NEWLY_HIDDEN' | 'UNMAPPED'

export type SidebarDiffRow = {
  label: string
  href: string
  key: string | null
  legacyVisible: boolean
  effectiveAllowed: boolean
  status: SidebarDiffStatus
}

export function diffSidebar(
  items: { label: string; href: string }[],
  persona: BaselinePersona,
  catalog: BaselineCatalogEntry[],
): SidebarDiffRow[] {
  const allowedSet = new Set(persona.allowed)

  return items.map((item) => {
    const entry = findCapabilityForPath(catalog, item.href)
    // The legacy sidebar renders an item purely from the role's own item list,
    // so presence in that list IS legacy visibility.
    const legacyVisible = true
    const effectiveAllowed = entry ? allowedSet.has(entry.key) : false

    const status: SidebarDiffStatus =
      !entry ? 'UNMAPPED'
      : legacyVisible && effectiveAllowed ? 'MATCH'
      : legacyVisible && !effectiveAllowed ? 'NEWLY_HIDDEN'
      : 'NEWLY_VISIBLE'

    return { label: item.label, href: item.href, key: entry?.key ?? null, legacyVisible, effectiveAllowed, status }
  })
}

/* ── 18. Aggregate reporting ───────────────────────────────────────────── */

export type DiffSummary = {
  totalComparisons: number
  counts: Record<DiffStatus, number>
  byRisk: Record<RiskLevel, number>
  byRole: Record<string, Record<DiffStatus, number>>
  byCategory: Record<string, Record<DiffStatus, number>>
}

export function summarize(diffs: PersonaDiff[]): DiffSummary {
  const counts: Record<DiffStatus, number> = { ...EMPTY_COUNTS }
  const byRisk: Record<RiskLevel, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, EXPECTED: 0 }
  const byRole: Record<string, Record<DiffStatus, number>> = {}
  const byCategory: Record<string, Record<DiffStatus, number>> = {}
  let total = 0

  for (const diff of diffs) {
    byRole[diff.personaId] ??= { ...EMPTY_COUNTS }

    for (const row of diff.rows) {
      total += 1
      counts[row.status] += 1
      byRisk[row.risk] += 1
      byRole[diff.personaId][row.status] += 1
      byCategory[row.category] ??= { ...EMPTY_COUNTS }
      byCategory[row.category][row.status] += 1
    }
  }

  return { totalComparisons: total, counts, byRisk, byRole, byCategory }
}

/** Every row at or above a given severity, for the "list them individually" report. */
export function rowsAtRisk(diffs: PersonaDiff[], levels: RiskLevel[]): (DiffRow & { personaId: string })[] {
  const wanted = new Set(levels)
  const out: (DiffRow & { personaId: string })[] = []

  for (const diff of diffs) {
    for (const row of diff.rows) {
      if (wanted.has(row.risk)) out.push({ ...row, personaId: diff.personaId })
    }
  }

  return out
}

/* ── 20. Cutover readiness gates ───────────────────────────────────────── */

export type CutoverGate = { name: string; pass: boolean; actual: number; detail: string }

/**
 * The hard gates that must all pass before Phase 2G. These encode the approved
 * rules; they do not fix anything, they only report.
 */
export function evaluateCutoverGates(diffs: PersonaDiff[], unmapped: string[]): CutoverGate[] {
  const summary = summarize(diffs)
  const critical = rowsAtRisk(diffs, ['CRITICAL'])
  const high = rowsAtRisk(diffs, ['HIGH'])

  const protectedRegressions = diffs.flatMap((d) =>
    d.rows.filter((r) => r.riskLevelOfPage === 'SYSTEM_PROTECTED' && r.status === 'NEWLY_ALLOWED'),
  )

  const aiRegressions = diffs.flatMap((d) =>
    d.rows.filter(
      (r) => r.category === 'technical_system' && r.status === 'NEWLY_ALLOWED' && d.role !== 'super_admin' && d.role !== 'tech_admin',
    ),
  )

  return [
    { name: 'CRITICAL mismatches = 0', pass: critical.length === 0, actual: critical.length, detail: 'ordinary persona gains a SYSTEM_PROTECTED page' },
    { name: 'HIGH mismatches = 0', pass: high.length === 0, actual: high.length, detail: 'leader-only surface gained without canonical leadership, or an unmapped route' },
    { name: 'UNMAPPED routes = 0', pass: unmapped.length === 0, actual: unmapped.length, detail: 'legacy dashboard path with no catalog capability' },
    { name: 'SYSTEM_PROTECTED regressions = 0', pass: protectedRegressions.length === 0, actual: protectedRegressions.length, detail: 'protected capability newly allowed' },
    { name: 'AI separation regressions = 0', pass: aiRegressions.length === 0, actual: aiRegressions.length, detail: 'non-root persona newly allowed a technical_system page' },
    { name: 'NEWLY_DENIED reviewed', pass: summary.counts.NEWLY_DENIED === 0, actual: summary.counts.NEWLY_DENIED, detail: 'access the legacy system grants but the new one does not — must be explicitly accepted' },
  ]
}
